{
	// WARNING! DO NOT EDIT THIS FILE! ANY CHANGES MADE WILL BE LOST!
	"doc_id" : "1XOPUV2TUbrr6ZMR5oGa7SPD4YoYIXxfehQbxKJ4XUYM",
	"email" : "egretfulherron@gmail.com",
	"resource_key" : "",
	"url" : "https://docs.google.com/open?id=1XOPUV2TUbrr6ZMR5oGa7SPD4YoYIXxfehQbxKJ4XUYM"
}